# Example of environment registry file
# Stored in: ~/.config/gvit/envs/{venv_name}.toml

[environment]
name = "gvit"
backend = "conda"
python = "3.11"
created_at = "2025-01-22T20:53:01.123456"

[repository]
path = "/Users/user/Documents/Proyectos/gvit"
url = "https://github.com/jaimemartinagui/gvit.git"

[deps]
_base = "requirements.txt"
dev = "requirements-dev.txt"
test = "requirements-test.txt"

[deps.installed]
# File hashes for change detection (first 16 chars of SHA256)
_base_hash = "a1b2c3d4e5f6g7h8"
dev_hash = "i9j0k1l2m3n4o5p6"
test_hash = "q7r8s9t0u1v2w3x4"
installed_at = "2025-01-22T20:53:15.789012"
